# Gaussian Proccess (GP) on M1 and S2 Site Data
We wish to determine the seasonal and diurnal cycles of supermicron aerosols/bioaerosols. In this notebook we focus on the seasonal trends. We will split the data up by seasons and fit a GP on a subset of the data. Using a confidence interval, we will determine if the data indicates seasonal cycles. 

In [ ]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import multivariate_normal
from scipy.spatial.distance import cdist
from scipy.special import kv, gamma
import itertools
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
import ipywidgets as widgets
from ipywidgets import interactive

os.environ["OMP_NUM_THREADS"] = "2"



def data_import(path1, delimiter):
    #locate file path and import data
    if delimiter == 'none':
        file1 = pd.read_csv(path1)
    else:   
        file1 = pd.read_csv(path1, delimiter=delimiter)
    return file1

def data_convert(file1, time_column_name: str):
    #convert timestamps to datetime format
    file1[time_column_name] = pd.to_datetime(file1[time_column_name])
   
    #handle missing values (NaN); fill with mean value
    file1.fillna(file1.mean(), inplace=True)

    return file1

def data_frequency(file1, desired_frequency: str, time_column_name: str):
    if desired_frequency == 'ten_minute':
        file1 = file1.resample('10T', on=time_column_name).mean()
    elif desired_frequency == '4_hourly':
        file1 = file1.resample('4h', on=time_column_name).mean()
    elif desired_frequency == 'hourly':
        file1 = file1.resample('h', on=time_column_name).mean()
    elif desired_frequency == 'twelve_hourly':
        file1 = file1.resample('12h', on=time_column_name).mean()
    elif desired_frequency == 'daily':
        file1 = file1.resample('D', on=time_column_name).mean()

    # Ensure the index is datetime
    file1.index = pd.to_datetime(file1.index)
    
    # Reset the index and name it 'Time(UTC)'
    file1.reset_index(inplace=True)
    file1.rename(columns={file1.index.name: time_column_name}, inplace=True)

    return file1


def time_to_sincos(df):
    sin_values = []
    cos_values = []

    for i in range(len(df)):
        sin_values.append(np.sin((2 * np.pi * i) / 365.25))
        cos_values.append(np.cos((2 * np.pi * i) / 365.25))
        
    df['Time_sin'] = sin_values
    df['Time_cos'] = cos_values
    
    return df

#trim data to desired collumns
def file_trim(file1, desired_collumns):
    file1 = file1[desired_collumns]
    return file1

#separate data by seasons
def data_split(file1, time_column_name: str):
    winter = file1[(file1[time_column_name] >= '2022-12-21') & (file1[time_column_name] < '2023-03-20')]
    spring = file1[(file1[time_column_name] >= '2023-03-20') & (file1[time_column_name] < '2023-06-21')]
    summer = file1[(file1[time_column_name] >= '2022-06-21') & (file1[time_column_name] < '2022-09-23')]
    autunm = file1[(file1[time_column_name] >= '2022-09-23') & (file1[time_column_name] < '2022-12-21')]
    return winter, spring, summer, autunm





# S2 site data importing and modeling 
Here we import and handle all of the data. s2 first, split the varying frequencies and seasons, then M1 data

In [ ]:
#importing s2 and m1 data sets
s2_site_data= data_import("C:\\Users\\396760\\lanl\\data\\ARMSAILS2_cleaned.csv", 'none')
m1_site_data = data_import("C:\\Users\\396760\\lanl\\data\\ARMSAILM1_cleaned.csv", 'none')

#data conversion and handling for m1, s2 data
s2_site_data, m1_site_data = data_convert(s2_site_data, 'Time(UTC)'), data_convert(m1_site_data, 'Time(UTC)')

#defining collumns and imp feature variables
collumns = ['Time(UTC)', 'sample_rh_pct', 'sample_temp_C', 'pm_1_ug_per_m3', 'Time_sin', 'Time_cos']
collumns1 = ['Time(UTC)', 'sample_rh_pct', 'sample_temp_C', 'pm_25_ug_per_m3', 'Time_sin', 'Time_cos']
features = ['sample_rh_pct', 'sample_temp_C', 'Time_sin', 'Time_cos']
s2_target_pm1 = m1_target_pm1 = ['pm_1_ug_per_m3']
s2_target_pm25 = m1_target_pm25 = ['pm_25_ug_per_m3']
s2_target_pm10 = m1_target_pm10 = ['pm_10_ug_per_m3']

In [ ]:
#defining datasets of differing frequencies in the following order : daily, 12 hourly, 4 hourly and hourly, 
s2_site_daily, m1_site_daily = data_frequency(s2_site_data, 'daily', 'Time(UTC)'), data_frequency(m1_site_data, 'daily', 'Time(UTC)')
s2_site_12hourly, m1_site_12hourly = data_frequency(s2_site_data, 'twelve_hourly', 'Time(UTC)'), data_frequency(m1_site_data, 'twelve_hourly', 'Time(UTC)')
s2_site_4hourly, m1_site_4hourly = data_frequency(s2_site_data, '4_hourly', 'Time(UTC)'), data_frequency(m1_site_data, '4_hourly', 'Time(UTC)')
s2_site_hourly, m1_site_hourly = data_frequency(s2_site_data, 'hourly', 'Time(UTC)'), data_frequency(m1_site_data, 'hourly', 'Time(UTC)')

#time to sin cos conversion
s2_site_daily, m1_site_daily = time_to_sincos(s2_site_daily), time_to_sincos(m1_site_daily)
s2_site_12hourly, m1_site_12hourly = time_to_sincos(s2_site_12hourly), time_to_sincos(m1_site_12hourly)
s2_site_4hourly, m1_site_4hourly = time_to_sincos(s2_site_4hourly), time_to_sincos(m1_site_4hourly)
s2_site_hourly, m1_site_hourly = time_to_sincos(s2_site_hourly), time_to_sincos(m1_site_hourly)

#trimming data to desired collumns
s2_site_daily, m1_site_daily = file_trim(s2_site_daily, collumns), file_trim(m1_site_daily, collumns)
s2_site_12hourly, m1_site_12hourly = file_trim(s2_site_12hourly, collumns), file_trim(m1_site_12hourly, collumns)
s2_site_4hourly, m1_site_4hourly = file_trim(s2_site_4hourly, collumns), file_trim(m1_site_4hourly, collumns)
s2_site_hourly, m1_site_hourly = file_trim(s2_site_hourly, collumns), file_trim(m1_site_hourly, collumns)

#splitting data by seasons

#daily
s2_winter_daily, s2_spring_daily, s2_summer_daily, s2_autunm_daily = data_split(s2_site_daily, 'Time(UTC)')
m1_winter_daily, m1_spring_daily, m1_summer_daily, m1_autunm_daily = data_split(m1_site_daily, 'Time(UTC)')
#12 hourly
s2_winter_12hourly, s2_spring_12hourly, s2_summer_12hourly, s2_autunm_12hourly = data_split(s2_site_12hourly, 'Time(UTC)')
m1_winter_12hourly, m1_spring_12hourly, m1_summer_12hourly, m1_autunm_12hourly = data_split(m1_site_12hourly, 'Time(UTC)')
#4 hourly
s2_winter_4hourly, s2_spring_4hourly, s2_summer_4hourly, s2_autunm_4hourly = data_split(s2_site_4hourly, 'Time(UTC)')
m1_winter_4hourly, m1_spring_4hourly, m1_summer_4hourly, m1_autunm_4hourly = data_split(m1_site_4hourly, 'Time(UTC)')
#hourly
s2_winter_hourly, s2_spring_hourly, s2_summer_hourly, s2_autunm_hourly = data_split(s2_site_hourly, 'Time(UTC)')
m1_winter_hourly, m1_spring_hourly, m1_summer_hourly, m1_autunm_hourly = data_split(m1_site_hourly, 'Time(UTC)')

#plots for s2 data sites at varying frequencies (PM1)

#daily
plt.figure(figsize=(10,5))
plt.plot(s2_winter_daily['Time(UTC)'], s2_winter_daily['pm_1_ug_per_m3'], label='Winter')
plt.plot(s2_spring_daily['Time(UTC)'], s2_spring_daily['pm_1_ug_per_m3'], label='Spring')
plt.plot(s2_summer_daily['Time(UTC)'], s2_summer_daily['pm_1_ug_per_m3'], label='Summer')
plt.plot(s2_autunm_daily['Time(UTC)'], s2_autunm_daily['pm_1_ug_per_m3'], label='Autunm')
plt.legend()
plt.show()

#12 hourly
plt.figure(figsize=(10,5))
plt.plot(s2_winter_12hourly['Time(UTC)'], s2_winter_12hourly['pm_1_ug_per_m3'], label='Winter')
plt.plot(s2_spring_12hourly['Time(UTC)'], s2_spring_12hourly['pm_1_ug_per_m3'], label='Spring')
plt.plot(s2_summer_12hourly['Time(UTC)'], s2_summer_12hourly['pm_1_ug_per_m3'], label='Summer')
plt.plot(s2_autunm_12hourly['Time(UTC)'], s2_autunm_12hourly['pm_1_ug_per_m3'], label='Autunm')
plt.legend()
plt.show()

#4 hourly
plt.figure(figsize=(10,5))
plt.plot(s2_winter_4hourly['Time(UTC)'], s2_winter_4hourly['pm_1_ug_per_m3'], label='Winter')
plt.plot(s2_spring_4hourly['Time(UTC)'], s2_spring_4hourly['pm_1_ug_per_m3'], label='Spring')
plt.plot(s2_summer_4hourly['Time(UTC)'], s2_summer_4hourly['pm_1_ug_per_m3'], label='Summer')
plt.plot(s2_autunm_4hourly['Time(UTC)'], s2_autunm_4hourly['pm_1_ug_per_m3'], label='Autunm')
plt.legend()
plt.show()

#hourly
plt.figure(figsize=(10,5))
plt.plot(s2_winter_hourly['Time(UTC)'], s2_winter_hourly['pm_1_ug_per_m3'], label='Winter')
plt.plot(s2_spring_hourly['Time(UTC)'], s2_spring_hourly['pm_1_ug_per_m3'], label='Spring')
plt.plot(s2_summer_hourly['Time(UTC)'], s2_summer_hourly['pm_1_ug_per_m3'], label='Summer')
plt.plot(s2_autunm_hourly['Time(UTC)'], s2_autunm_hourly['pm_1_ug_per_m3'], label='Autunm')
plt.legend()
plt.show()



visualizing our choice of kernel

In [ ]:
def visualize_kernel_function_space(kernel, x_range, n_functions, **kernel_params):
    # Create a grid of x values
    X = np.atleast_2d(x_range).T

    # Compute the kernel matrix
    K = kernel(X, X, **kernel_params)

    # Clear the plot
    plt.figure(figsize=(10, 6))
    
    # Generate functions
    for _ in range(n_functions):
        # Draw samples from a multivariate normal distribution
        f = multivariate_normal.rvs(mean=10*np.ones(X.shape[0]), cov=K)
        
        # Plot the function
        plt.plot(x_range, f)

    plt.xlabel('X')
    plt.ylabel('Function Value')
    plt.title(f'Functions Sampled from {kernel.__name__}')
    plt.grid(True)
    plt.show()

def white_noise_kernel(x1, x2, variance=2.0):
    return variance * np.eye(len(x1))

def rbf_kernel(x1, x2, length_scale=1.0, variance=1.0):
    # Compute the pairwise squared distances between the inputs
    sq_dists = cdist(x1, x2, 'sqeuclidean')
    
    # Compute the kernel
    return variance * np.exp(-0.5 * sq_dists / length_scale**2)

def periodic_kernel(x1, x2, length_scale=1.0, variance=1.0, period=1.0):
    # Compute the pairwise squared distances between the inputs
    sq_dists = cdist(x1, x2, 'sqeuclidean')
    
    # Compute the kernel
    return variance * np.exp(-2 * np.sin(np.pi * np.sqrt(sq_dists) / period)**2 / length_scale**2)

def matern_kernel(x, x_star, length_scale=1.0, nu=0.5, variance=1.0):
    dists = cdist(x / length_scale, x_star / length_scale, metric='euclidean')
    
    if nu == 0.5:
        K = np.exp(-dists)
    elif nu == 1.5:
        sqrt3 = np.sqrt(3)
        K = (1.0 + sqrt3 * dists) * np.exp(-sqrt3 * dists)
    elif nu == 2.5:
        sqrt5 = np.sqrt(5)
        K = (1.0 + sqrt5 * dists + (5.0 / 3.0) * (dists ** 2)) * np.exp(-sqrt5 * dists)

    return variance * K

def sum_kernel(x1, x2, variance, length_scale, nu):
    return white_noise_kernel(x1, x2, variance=variance) + matern_kernel(x1, x2, variance=variance, length_scale=length_scale, nu=nu) + periodic_kernel(x1, x2, variance=variance, length_scale=length_scale, period=period)

x_space = np.linspace(0, 10, 100)
num_of_functions = 3

# Create sliders for kernel parameters
def plot_white_noise_kernel(variance):
    visualize_kernel_function_space(white_noise_kernel, x_space, num_of_functions, variance=variance)

def plot_rbf_kernel(length_scale, variance):
    visualize_kernel_function_space(rbf_kernel, x_space, num_of_functions, length_scale=length_scale, variance=variance)

def plot_periodic_kernel(length_scale, variance, period):
    visualize_kernel_function_space(periodic_kernel, x_space, num_of_functions, length_scale=length_scale, variance=variance, period=period)

def plot_matern_kernel(length_scale, nu, variance):
    visualize_kernel_function_space(matern_kernel, x_space, num_of_functions, length_scale=length_scale, nu=nu, variance=variance)

def plot_sum_kernel(variance, length_scale, nu, period):
    visualize_kernel_function_space(sum_kernel, x_space, num_of_functions, variance=variance, length_scale=length_scale, nu=nu, period=period)

# Create interactive widgets
interactive_plot_white_noise = interactive(plot_white_noise_kernel, variance=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=2.0))
interactive_plot_rbf = interactive(plot_rbf_kernel, length_scale=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0), variance=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0))
interactive_plot_periodic = interactive(plot_periodic_kernel, length_scale=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0), variance=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0), period=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0))
interactive_plot_matern = interactive(plot_matern_kernel, length_scale=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0), nu=widgets.FloatSlider(min=0.5, max=2.5, step=1.0, value=0.5), variance=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0))
interactive_plot_sum = interactive(plot_sum_kernel, variance=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0), length_scale=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0), nu=widgets.FloatSlider(min=0.5, max=2.5, step=1.0, value=0.5), period=widgets.FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0))
display(interactive_plot_white_noise)
display(interactive_plot_rbf)
display(interactive_plot_periodic)
display(interactive_plot_matern)
display(interactive_plot_sum)


In [ ]:

def covariance_matrix(x, x_star, kernel, **kernel_params):
    return kernel(x, x_star, **kernel_params)

def run_gp_regression(X, y, X_star, kernel, **kernel_params):

    # Compute the covariance matrices
    K = covariance_matrix(X, X, kernel, **kernel_params)
    K_star = covariance_matrix(X, X_star, kernel, **kernel_params)
    K_star_star = covariance_matrix(X_star, X_star, kernel, **kernel_params)
    
    # Compute the Cholesky decomposition of K
    L = np.linalg.cholesky(K + 1e-6 * np.eye(len(X)))
    
    # Compute the mean of the posterior predictive distribution
    alpha = np.linalg.solve(L.T, np.linalg.solve(L, y))
    f_star_mean = K_star.T @ alpha
    
    # Compute the variance of the posterior predictive distribution
    v = np.linalg.solve(L, K_star)
    f_star_var = K_star_star - v.T @ v
    
    return f_star_mean, f_star_var

def RMSE_calc(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

def plot_gp(X, y, X_star, y_star, f_star_mean, f_star_var, kernel_name):
    # Plot the training data
    plt.figure(figsize=(10, 6))
    plt.scatter(X, y, color='black', label='Training Data')
    
    # Plot the true function
    plt.plot(X_star, y_star, color='blue', label='True Function')
    
    # Plot the mean of the posterior predictive distribution
    plt.plot(X_star, f_star_mean, color='red', label='Mean of Posterior Predictive')
    
    # Plot the 95% confidence interval
    plt.fill_between(X_star, f_star_mean - 1.96 * np.sqrt(np.diag(f_star_var)), f_star_mean + 1.96 * np.sqrt(np.diag(f_star_var)), color='red', alpha=0.2, label='95% Confidence Interval')
    
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.title(f'Gaussian Process Regression with {kernel_name}')
    plt.legend()
    plt.grid(True)
    plt.show()

In [26]:
#Pick a random subset of the s2_autumn_daily data
X = s2_autunm_daily[features].values
y = s2_autunm_daily['pm_1_ug_per_m3'].values
X, y = np.array(X), y.reshape(-1, 1)


       


[[ 5.70989333e+01  1.08222097e+01  9.86146248e-01 -1.65878199e-01]
 [ 4.22430750e+01  1.12089618e+01  9.83146974e-01 -1.82816925e-01]
 [ 3.26547451e+01  1.28113882e+01  9.79856770e-01 -1.99701553e-01]
 [ 2.84274167e+01  1.40744569e+01  9.76276611e-01 -2.16527085e-01]
 [ 3.59275500e+01  1.38221729e+01  9.72407556e-01 -2.33288544e-01]
 [ 4.71497146e+01  1.23835257e+01  9.68250750e-01 -2.49980969e-01]
 [ 4.81332090e+01  1.16796097e+01  9.63807423e-01 -2.66599421e-01]
 [ 6.39657646e+01  9.23182569e+00  9.59078890e-01 -2.83138981e-01]
 [ 7.77019396e+01  5.75215139e+00  9.54066550e-01 -2.99594756e-01]
 [ 8.10055417e+01  5.83488889e+00  9.48771886e-01 -3.15961877e-01]
 [ 7.81243340e+01  5.61884236e+00  9.43196466e-01 -3.32235499e-01]
 [ 6.05938292e+01  8.03130972e+00  9.37341938e-01 -3.48410807e-01]
 [ 4.96280486e+01  7.91240625e+00  9.31210036e-01 -3.64483015e-01]
 [ 5.76202236e+01  8.51429167e+00  9.24802574e-01 -3.80447366e-01]
 [ 5.16488896e+01  9.13146042e+00  9.18121448e-01 -3.96299137e